/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package entornosjava;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public void appSuma() {

    }
    public static void main(String[] args) {
        System.out.println("Pedro Martinez");
    }
}